import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import { randomUUID } from "crypto";

import { BalanceTransactionsRepository } from "@/repositories/balance_transactions.repository";
import { BalancesRepository } from "@/repositories/balances.repositorty";
import { supabase } from "@/lib/supabase-client";

// Exercises BalanceTransactionsRepository against a real local
// Supabase/Postgres instance (`pnpm supabase:start`). No Express/HTTP
// involved - this is the tier that can catch drift between
// BalanceTransactionSchema and the real table, or the cursor pagination
// query skipping/duplicating rows against real UUIDv7 ids.
describe("BalanceTransactionsRepository (integration, real local Supabase)", () => {
    const repo = new BalanceTransactionsRepository();
    const balancesRepo = new BalancesRepository();

    let orgId: string;
    let userId: string;
    let authUserId: string;
    let balanceId: string;

    beforeAll(async () => {
        const { data: org, error: orgError } = await supabase
            .from("organisations")
            .insert({ name: `integration-org-${randomUUID()}` })
            .select("id")
            .single();
        if (orgError) throw orgError;
        orgId = org.id;

        const { data: authUser, error: authError } = await supabase.auth.admin.createUser({
            email: `integration-${randomUUID()}@test.com`,
            password: "password123",
            email_confirm: true,
        });
        if (authError) throw authError;
        authUserId = authUser.user!.id;
        userId = authUserId;

        const { error: userError } = await supabase
            .from("users")
            .insert({ id: userId, first_name: "Integration", last_name: "Test" });
        if (userError) throw userError;
    });

    afterEach(async () => {
        await supabase.from("balances").delete().eq("user_id", userId);
    });

    afterAll(async () => {
        await supabase.from("users").delete().eq("id", userId);
        await supabase.from("organisations").delete().eq("id", orgId);
        await supabase.auth.admin.deleteUser(authUserId);
    });

    describe("findByBalanceId", () => {
        it("returns an empty page for a balance with no transactions", async () => {
            const balance = await balancesRepo.create({ org_id: orgId, user_id: userId, balance: 100 });
            balanceId = balance!.id;

            const page = await repo.findByBalanceId(balanceId, { page_size: 25 });

            expect(page).toEqual({ data: [], has_more: false, next_cursor: null });
        });

        it("returns an empty page for a balance id that does not exist", async () => {
            const page = await repo.findByBalanceId(randomUUID(), { page_size: 25 });

            expect(page).toEqual({ data: [], has_more: false, next_cursor: null });
        });

        it("returns transactions newest first, generated by fn_increment_balance/fn_decrement_balance", async () => {
            const balance = await balancesRepo.create({ org_id: orgId, user_id: userId, balance: 100 });
            balanceId = balance!.id;

            await balancesRepo.increment(balanceId, 10);
            await balancesRepo.redeem(balanceId, 5);
            await balancesRepo.increment(balanceId, 20);

            const page = await repo.findByBalanceId(balanceId, { page_size: 25 });

            expect(page.has_more).toBe(false);
            expect(page.next_cursor).toBeNull();
            expect(page.data).toHaveLength(3);
            expect(page.data.map((t) => t.type)).toEqual(["credit", "debit", "credit"]);
            expect(page.data.map((t) => t.amount)).toEqual([20, 5, 10]);
            // id DESC - newest first
            const ids = page.data.map((t) => t.id);
            expect([...ids].sort().reverse()).toEqual(ids);
        });

        it("walks the full cursor sequence with no duplicates or skips across multiple pages", async () => {
            const balance = await balancesRepo.create({ org_id: orgId, user_id: userId, balance: 1000 });
            balanceId = balance!.id;

            const transactionCount = 7;
            for (let i = 0; i < transactionCount; i++) {
                await balancesRepo.increment(balanceId, 1);
            }

            const seen: string[] = [];
            let cursor: string | undefined;
            let hasMore = true;

            while (hasMore) {
                const page = await repo.findByBalanceId(balanceId, {
                    page_size: 3,
                    starting_after: cursor,
                });
                seen.push(...page.data.map((t) => t.id));
                hasMore = page.has_more;
                cursor = page.next_cursor ?? undefined;
            }

            expect(seen).toHaveLength(transactionCount);
            expect(new Set(seen).size).toBe(transactionCount);
            // strictly decreasing - id DESC across the whole walk, no skips/dupes
            for (let i = 1; i < seen.length; i++) {
                expect(seen[i]! < seen[i - 1]!).toBe(true);
            }
        });
    });
});
